### ISSUE TITLE
Delphi 2007 not supported

### ISSUE THREAD

**Issue by guoqingaa** [joaoduarte19/sqlcollection#2]
It's a great project, but it doesn't support Delphi 2007, There is no RTTI, and generics in d2007，Do you want it to support D7, d2007

**Comment by joaoduarte19** [comment]
For now I do not intend to offer compatibility with old delphi. My intention is that this component supports versions of delphi XE7 and later.

**Comment by guoqingaa** [comment]
Oh, this is really frustrating news.
